### ISSUE TITLE
How can i fire an event from within one of the states?

### ISSUE THREAD

**Issue by tomerb15** [fschaefer/Stately.js#15]
Hi, Thanks for this awesome lib!

I was wondering if i can fire an event from within one of the states, E.G:
I have the following state machine:
```
var statesObject = {
    1:{
        tutorial: function(){
            this.foo();
        }
    },
    2:{
        tutorial: function(){
            if(someCondition){
                  //move the stateMachine to state1 which calls foo();
            }
        }
    },
   foo: function(){//some logic}
}
```

I can't make it to work, if the condition on state 2 is true, i could'nt find a way to move the machine to state 1 + call its tutorial function which calls foo() using the `this` object.
Any easy way to achieve that?

Thanks for the help!

**Comment by fschaefer** [comment]
Hey,

you might want to re-read the last paragraph of [transitions](https://github.com/fschaefer/Stately.js#transitions).

`this['1'].tutorial()` should work, to call the tutorial event of the `1` state.

Flo

**Comment by tomerb15** [comment]
Hey Florian, 

I'm sorry that i wasn't so clear regarding my problem.
The problem was after calling `this['1'].tutorial()`.

Inside state 1 we have `this.foo()` however, `this` reference to state `1` object and not the entire stateMachine object. This results an exception as `this.foo()` is not a function.

**Comment by fschaefer** [comment]
`The property names of the statesObject are the states of the machine.` So attaching `foo` as function to the `stateObject` isn't really encouraged. Can you provide an example showing the issue, i.e. throwing the exception?

**Comment by tomerb15** [comment]
I fixed the problem by taking your approach and moved the function `foo` outside the states object leaving it with only states. I agree that attaching `foo` as a function was a bad idea :)

However, if someone will still want to use my functionality above, he can't because `this` points to different object every time:
1. If the state machine is at state 1 and we call `stateMachine.tutorial()`, `this` will point to the `stateObject`.
2. If we are at state 2 and we call `this['1'].tutorial()` then `this` points to the object `1` and not the entire `stateObject`

**Comment by fschaefer** [comment]
You are right: `this['1'].tutorial()` is just wrong. You have to maintain the `this` reference yourself with `this['1'].tutorial.call(this)` like in the example in the readme.
