### ISSUE TITLE
Publish last releases on npm

### ISSUE THREAD

**Issue by yamsellem** [fschaefer/Stately.js#18]
Can you please publish releases on npm?
Only 0.1.1 and 0.1.2 are available right now (`npm view stately`).

Pulling the tags and `npm publish --tag <version>` is plenty for npm to know that they exist.
Thanks for the great work ;-).

**Comment by yamsellem** [comment]
My bad, it seems that `stately` is registered too, but that `stately.js` is the correct name.
We may ask @jchris [to share the repo name](https://docs.npmjs.com/misc/disputes), his last release if 4 years old, and the name is misleading.

**Comment by rowanu** [comment]
I do the publishing to NPM for @fschaefer.

I'm happy to ask about the simpler package name for `npm` if @fschaefer is fine with it?

**Comment by jchris** [comment]
I'm not particular about package names, but it will be a fair amount of
work to set up my dev toolchain to modify some dependent packages I have.
Unless what you're doing will start with a version number bump, so old
users of my package are unaffected. In the latter case, handing the name
over to you sounds like no problem to me.

Chris
On Tue, May 3, 2016 at 4:28 PM rowan <notifications@github.com> wrote:

> I do the publishing to NPM for @fschaefer <https://github.com/fschaefer>.
>
> I'm happy to ask about the simpler package name for npm if @fschaefer
> <https://github.com/fschaefer> is fine with it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fschaefer/Stately.js/issues/18#issuecomment-216695693>
>
-- 
971-235-1414
http://twitter.com/jchris

**Comment by fschaefer** [comment]
@rowanu, sure, you are free to decide about the `npm` package name and to do the necessary commits.

**Comment by rowanu** [comment]
Given the extra work that will be required (on both sides), the fact that it already matches the repo name, and @yamsellem found the package in the end, I'm inclined keep the status quo for now.

If more people have trouble finding the package in the future then I'll do the work needed to update it.
