### ISSUE TITLE
Update the api slightly

### ISSUE THREAD

**Issue by yamsellem** [fschaefer/Stately.js#19]
I really like the simplicity and clarity of your state machine.
There is one little thing which may improve it form an inch.

Don't you think turning:

``` javascript
radio.onleaveSTOPPED = function (event, oldState, newState) {};
radio.onenterSTOPPED = function (event, oldState, newState) {};
radio.onPLAYING = function (event, oldState, newState) {};
```

Into:

``` javascript
radio.on('leave', 'STOPPED', function (event, oldState, newState) {});
radio.on('enter' 'STOPPED', function (event, oldState, newState) {});
radio.on('PLAYING', function (event, oldState, newState) {});
```

Make notifications more standard?
Thanks for the consideration (_I may offer a pull request, the update seems straightforward_).

**Comment by fschaefer** [comment]
I like this idea. It could replace the old `hooks` and `notifications`, if it would work for `states` and `events`.  A pull request is very welcome.

**Comment by markmanx** [comment]
I might be missing something here, but wouldn't it be even easier to allow onLeave and onEnter to be defined in the states object, e.g. 

```
var machine = Stately.machine({
    'STATE0': {
        onEnter: function () {
            ...
        }
    }
});
```

Personally, I switched over from Machinajs to using Stately because Machina requires dependencies and is a little bit chunkier, but having onEnter and onLeave in the states object is what I miss most about Machina.js.

**Comment by fschaefer** [comment]
With release 2.0.0 the API has changed to state object functions `onEnter`, `onLeave`, `onBefore<eventname>` and `onAfter<eventname>` as proposed by @markmanx . The old `hook` and `notification` API with `bind()` and the alternative way has been removed.
